# Generated by Django 3.2.4 on 2021-06-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0002_auto_20210610_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
