# Generated by Django 3.2.4 on 2021-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0003_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
