# Generated by Django 3.2.4 on 2021-06-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wish', '0004_wish_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='taker',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='url',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wish.wish')),
            ],
        ),
    ]
