# Generated by Django 3.2.4 on 2021-06-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wish', '0005_auto_20210610_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
